### ISSUE TITLE
Environment Setup Process Missing A Step

### ISSUE THREAD

**Issue by Phlosioneer** [RustDT/RustDT#114]
In the steps listed to setup the development environment, the project won't build as-is after selecting the target. I had to right click the project dir, go to configure, and enable PDE capabilities. Then it would build.

Not sure if this should work out-of-the-box and is a configuration issue, or if it's just another step that should be added to the readme.

**Comment by bruno-medeiros** [comment]
Hum, nope, if you import using "Existing projects into workspace" , all projects should be configured already as PDE projects. The few projects that are not configured so are not mean to be plug-in projects (like the documentation project).

The issue might be because recently the projects got nested on a top-level parent project. Did you make sure you enabled "Search for nested projects" ?

**Comment by Phlosioneer** [comment]
> "Search for nested projects"

This did the trick. Perhaps add a note to the readme?
