### ISSUE TITLE
Preferences appear to be per workspace, not global

### ISSUE THREAD

**Issue by mcharsley** [RustDT/RustDT#148]
I've set up my preferences and everything works. I then Switch Workspace and the rust-dt preferences are blank. Switch back to my original workspace and settings are restored. Is there a way to set them at global level so I don't need to jump through the hoops for each workspace?

This is on Version: Neon.2 (4.6.2)

**Comment by bruno-medeiros** [comment]
This is how Eclipse works: preferences are per workspace, not global. And yeah, that is kinda lame, would be better otherwise.

One could make a workaround in RustDT preferences to make them apply globally, but, it might be weird cause that would only work for the RustDT preferences and not the rest of the Eclipse preferences.

Otherwise you can try some things like this: http://stackoverflow.com/questions/8383243/eclipse-global-preferences , or copy the Eclipse workspace `.metadata` dir to the new workspace whenever you create a new workspace.

**Comment by mcharsley** [comment]
You're quite right sorry. I was confusing global vs workspace settings with
workspace vs project-specific settings :-(

sorry for wasting your time, and thanks for writing RustDT
