### ISSUE TITLE
Problem with RustDT while building the project.

### ISSUE THREAD

**Issue by ghost** [RustDT/RustDT#67]
I have a sample project with main file. When I tried to build the project I'm getting this error. But when I tried from the terminal, it's working as expected.

====================  Starting Rust build  ====================
***********\*  Building Rust project: Sample_App  ************

> > Running: /usr/local/bin/cargo build
> >   ^^^ Terminated, exit code: 0 ^^^
> > Running: /usr/local/bin/cargo test --no-run
> >    Compiling hello_world v0.0.1 (file:///home/machine/Playground/Sample_App)
> > src/main.rs:1:1: 3:2 warning: function is never used: `main`, #[warn(dead_code)] on by default
> > src/main.rs:1 fn main() {
> > src/main.rs:2     println!("Hello, world!");  
> > src/main.rs:3 }
> >   ^^^ Terminated, exit code: 0 ^^^
> > ***********\*  Build terminated.  ***********

**Comment by ghost** [comment]
I have fixed the above issue. While installing RustDT plugin, make sure you have installed the PDE plugin which will fix the issue. 

Steps :
1. Go to Help > Install New Software
2. Choose "All available software" in "Work with" field
3. Type PDE in the filter list and install the eclipse plugin and enjoy :+1:

**Comment by bruno-medeiros** [comment]
I doubt installing PDE made any difference here.

The issue is that two build actions are performed per Rust project build: The normal `cargo build` and `cargo test --no-run`. The latter one unfortunately generates a warning for compilation, hopefully that issue can be resolved later, but it's more of a Rust limitation. In the meanwhile, you can disable the tests build target, on the context menu option "Enable for workspace build":
![02e47ae85be19a2faace34cbaa072989c2e15132](https://cloud.githubusercontent.com/assets/4324232/10138059/7ee1e032-65f4-11e5-9f9a-a6eb1267dbb6.png)

**Comment by ghost** [comment]
Okay Cool, Thanks for the update.
