### ISSUE TITLE
POM-less build

### ISSUE THREAD

**Issue by Boereck** [RustDT/RustDT#91]
Hi,

Since Tycho 0.24 there is a feature called POM-less build, which in turn requires Maven 3.3. For the Travis CI build this will probably require a manual installation of Maven 3.3.x.
https://wiki.eclipse.org/Tycho/Release_Notes/0.24#POM-less_Tycho_builds
This feature is not actually getting rid of all POM files, but at least reduces the amount of POM files and the respective duplication between `MANIFEST.MF` and `pom.xml` files. This makes creation and refactoring of plug-in projects less error prone. It is very easy to use, simply create file `.mvn/extensions.xml` in the repository root and add this content:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<extensions>
  <extension>
    <groupId>org.eclipse.tycho.extras</groupId>
    <artifactId>tycho-pomless</artifactId>
    <version>0.24.0</version>
  </extension>
</extensions>
```

Now all `pom.xml` files can be removed from `plugin_*` projects. If this is desired, I can provide a pull-request with this change.

**Comment by bruno-medeiros** [comment]
Yeah, I know about this. I actually tried it a few weeks ago (since on Windows it actually requires Maven 3.3.7+ or so, due to a bug), however I dropped the idea because it only works for simple pom.xml's that only define groupId/artifactId/version. Unfortunately for RustDT and other projects, some plugins (like plugin_ide.core.tests/ for example) define additional Tycho configuration that still requires a pom. So I kinda dropped the idea because it doesn't fully solve the problem. (Unfortunately, simply omitting the groupId/artifactId/version from those pom's doesn't work either. If a pom exists, nothing is inferred, one has to supply all the pom information

**Comment by Boereck** [comment]
Yep, it only works for no-config pom files. In the current project configuration you get rid of four pom files. Unfortunately it can seem confusing or inconsistent when some projects do have poms and some don't. I guess it is a matter of preference, whether this is considered a good thing or not.

**Comment by bruno-medeiros** [comment]
Yeah, my preference is also that it is a bit inconsistent to have some poms but not others. So I'd rather not do the pom-less thing. Plus, some of the pom-less plugins might need configuration in the future.

That said, I would welcome some way where the artificats didn't have to replicate the version specifier in so many places. (I don't mind the duplication of groupId and artifactId that much because they don't change over time). One thing I tried was to use a variable for the version, defined in the parent POM. But when compiling Maven puts out a warning saying that such is a bad practice, and might be deprecated and not allowed in the future. So I dropped that idea too.

**Comment by bruno-medeiros** [comment]
If you have an idea that works, let me know. But for now I've stopped trying to find a way, not worth the time.

**Comment by Boereck** [comment]
That's exactly my experience. Maybe at some point in the future the POM-less feature also allows defining some kind of POM-fragment for everything not inferable from OSGi/Eclipse configuration.

**Comment by Boereck** [comment]
I think we can close this issue and re-open if there is a better and more consistent way to get rid of "double entry accounting" in POM and OSGi/Eclipse config files.
