### ISSUE TITLE
Feature Request: Provide support to add more than one source folders

### ISSUE THREAD

**Issue by nibin** [RustDT/RustDT#98]
Hi,

I was looking for a good editor for Rust and being an eclipse user, I found this as the best fit for my purpose. I wanted to study the code base of redox-os[1] using Eclipse and somehow I am not able to do that. The code base of redox doesn't use the conventional 'src' folder. redox project has many source folders and I would like to add these source folders to get the RUST perspective to it.

Eclipse for Java/C/C++ allows to alter the build path and add different source folders. It would be great if RustDT can also support multiple source folders.

[1] https://github.com/redox-os/redox

**Comment by bruno-medeiros** [comment]
I don't think this will happen.

As far as things go, the only thing RustDT could do currently with the possibility of configuring additional source folders, is to display a different icon in the Project Explorer, which is really not a significant feature. 

That's because unlike Eclipse's Java support (JDT) and C/C++ support (CDT), RustDT uses external tools for semantic analysis, like Racer. As such, there is little point in configuring additional source folders in RustDT, if the external tools don't understand them. 

If there is some problem with using code completion, because of the source folder structure of the Redox project, then that is an issue that will likely have to be fixed in https://github.com/phildawes/racer first.
